####
#FAMILY
####
setwd("~/Dropbox/projects/AJH_AFRODYN/annonaceae_family/")
#Here, set the file name of the table generated by get_seq_lengths.py
sample.filename = "test_seq_lengths.txt"
#use their script to import to ensure correct ref lengths
sample.data= as.matrix(read.table(sample.filename,header=T,row.names=1,sep="\t"))

#set length of reference exon
reference.len = as.numeric(sample.data[1,])

#extract only sample exon lengths
sample.len = sample.data[2:length(sample.data[,1]),]

#calculate percentage of exon recovered for each exon in each individual
percent.len= sweep(sample.len, 2, reference.len, "/")
percent.len = ifelse(percent.len>1,1,percent.len)
percent.len.0.75 <- percent.len

# if percentage exon length recovered is >= 75% make value 1
# if not make value 0
percent.len.0.75[percent.len.0.75>=0.75] = 1
percent.len.0.75[percent.len.0.75<0.75] = 0

#For each exon calculate number of individuals with >= 75% of exon
col <- colSums(percent.len.0.75 != 0)

#Calculate % individuals with >= 75% of exon for each exon
col <- col / (length(sample.data[,1])-1) # -1 for meanlength
head(col)
table(col>=0.75)


#Extract only 75_75 exons from original dataset
length7575<-sample.data[,col>=0.75]

#Density plot of exon lengths with rug of actual exon lengths
d <- density(as.numeric(length7575[1,])) 
plot(d)
rug(as.numeric(length7575[1,]), ticksize = 0.03, side = 1, lwd = 0.5, col = par("fg"),
    quiet = getOption("warn") < 0)

#Get a list of names of 75_75 exons
fam<-names(length7575[1,])
fam

#Copy list of names into a file, and modify to the format shown in README
data.frame(fam)